name: Generate Done Log

on:
  push:
    branches:
      - dev # Change this to your main branch name

jobs:
  generate-log:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./.vscode
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check files
      run: |
        echo "Contents of todo.todo:"
        cat todo.todo
        echo "Contents of issues.todo:"
        cat issues.todo
      
    - name: Generate Log
      run: |
        grep "@done$" todo.todo issues.todo >> done_log.txt

    - name: Wait for file creation (optional)
      run: |
        sleep 5  # Wait for 5 seconds
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: done_log
        path: done_log.txt